---
title: "Exploratory Data Analysis of `Orthofinder` results "
subtitle: 'Simulated dataset generated by `Alf`'
author: ""
date: ""
output: 
  html_document:
    code_folding: hide
    code_download: true
    toc: true                  # table of content true
    toc_depth: 3               # upto three depths of headings (specified by #, ## and ###)
    toc_float: true
    number_sections: true     # if you want number sections at each table header
    theme: yeti              # many options for theme, this one is my favorite.
    highlight: tango           # specifies the syntax highlighting style
    #css: my.css               # you can add your custom css, should be in same folder
    # override defaults by calling with custom params from command line https://bookdown.org/yihui/rmarkdown/params-knit.html 15.3.2
---

# Dependencies

```{r}
library(Rfast)
library(gamlss)
library(MASS)
library(magrittr)
library(plotly)
library(cowplot)
library(data.table)
library(GGally)
```


# Summary statistics for the datasets

```{r}
ortho_results <- data.table::fread("data/stats167.csv")
skimr::skim(ortho_results)
DataExplorer::plot_str(ortho_results) 
```


# Correlation multiplot for variable pairs (density included)

```{r, message=FALSE}

ggcor <- GGally::ggpairs(ortho_results, title = "Correlation matrix plot (diagonal with estimated density)")
ggcor
```


# Pearson correlation between variable pairs (heatmap)

```{r}
 GGally::ggcorr(ortho_results, method = c("everything", "pearson"), label = TRUE) 
```

```{r}
dplyr::glimpse(ortho_results)
```



```{r}
head(ortho_results)
```



# Scatter plot for 

```{r}
ggsubtitle_custom_color = '#A9BACA' 
ggtitle_custom_color    = '#4A637B' 
ggcaption_custom_color  = '#A9BACA' 
h = 10000
# alpha plot

alpha_plot <-
  ggplot2::ggplot(data = ortho_results) + aes(x =alpha, 
                                              y = orthogroups,
                                              color = scalar) + 
  geom_point() + 
#  geom_hline(aes(yintercept = h, colour = "red")) +
#  geom_text(aes(0, h ,label = h, vjust = -1)) +
  
  # // layer 6:  Setting annotation for title, subtitle, caption
  labs(title     = "Title",
      subtitle   = "Subtitle",
      caption    = "Caption")   +
  
  theme(text = element_text(family = 'Helvetica',
                          color = '#000000')
      ,plot.title    = element_text(color = ggtitle_custom_color   , size = 14, face = "bold" , hjust = 0.5)
      ,plot.subtitle = element_text(color = ggsubtitle_custom_color, size = 9                , hjust = 1)
      ,plot.caption  = element_text(color = ggsubtitle_custom_color, size = 7, face = "italic")
      ,legend.position = "none") +
  scale_color_gradient2(midpoint=mean(ortho_results$scalar), 
                        low ="red",
                        mid ="white",
                        high ="blue",
                        space ="Lab" )
  
# +
#   scale_x_continuous(breaks = pretty(ortho_results$alpha, n = 10)) +
#   scale_y_discrete(breaks = pretty(ortho_results$orthogroups, n = 20))


  
# scalar plot
scalar_plot <- ggplot2::ggplot(data = ortho_results) + aes(x = scalar, 
                                                           y = orthogroups,
                                                           color = alpha ) + 
  geom_point() +
#  geom_hline(aes(yintercept = h, colour = "red")) +
#  geom_text(aes(0, h ,label = h, vjust = -1)) +
  
  # // layer 6:  Setting annotation for title, subtitle, caption
  labs(title     = "Title",
      subtitle   = "Subtitle",
      caption    = "Caption")   +
  
  theme(text = element_text(family = 'Helvetica',
                          color = '#000000')
      ,plot.title    = element_text(color = ggtitle_custom_color   , size = 14, face = "bold" , hjust = 0.5)
      ,plot.subtitle = element_text(color = ggsubtitle_custom_color, size = 9                , hjust = 1)
      ,plot.caption  = element_text(color = ggsubtitle_custom_color, size = 7, face = "italic")
      ,legend.position = "none") +
    scale_color_gradient2(midpoint=mean(ortho_results$alpha), 
                        low ="red",
                        mid ="white",
                        high ="blue",
                        space ="Lab" )
# +
#   scale_x_continuous(breaks = pretty(ortho_results$scalar, n = 10)) +
#   scale_y_continuous(breaks = pretty(ortho_results$orthogroups, n = 20))



plot_grid(alpha_plot, scalar_plot, ncol = 1, nrow = 2)
```


# 3D Scatter plot of scalar, alpha, orthogroups

```{r}
cam.zoom = 1
ver.angle = 90
plotly::plot_ly(data = ortho_results,
                x=~scalar, 
                z=~orthogroups, 
                y=~alpha,
                type="scatter3d", 
                mode="markers", 
                color = ~orthogroups) %>%
  layout(    title = "3D Scatter plot of scalar, alpha, orthogroups",
             scene = list(xaxis = list(title = 'scalar'),
                     yaxis = list(title  = 'alpha'),
                     zaxis = list(title  = 'orthogroups')))


```

# Forward regression with `RFast`

```{r}
class(as.matrix(ortho_results[,c("alpha","scalar")]))

Rfast::cor.fsreg(ortho_results$orthogroups, 
                 as.matrix(ortho_results[,c("alpha","scalar")]), 
                 ystand = TRUE, 
                 xstand = TRUE, 
                 threshold = 0.00005, 
                 tolb = 2, 
                 tolr = 0.02, 
                 stopping = "BICR2") 

```


# Binomial models (and quasi poisson because less assumptions = <3 )

```{r}


Rfast::qpois.reg(ortho_results$all_species_single_copy, ortho_results$orthogroups, full = FALSE, tol = 1e-09,maxiters = 100)


quasi <- glm(ortho_results$orthogroups~ortho_results$scalar, family=quasipoisson) #quasipoisson
sum_quasi <- summary(quasi) 

df = 3 # three model parameters: a,b, and phi
phi.fit = sum_quasi$dispersion #fitted phi value (aka dispersion) from summary(quasi)
mu.fit = quasi$fitted.values 

#dnbinom = negbin density, log=T returns log probabilities
AIC_quasi = 2*df - 2*sum(dnbinom(ortho_results$orthogroups, 
                           mu=mu.fit, 
                           size = mu.fit/(phi.fit - 1), 
                           log=T))

AIC_quasi

glmNB <- MASS::glm.nb(ortho_results$orthogroups~ortho_results$scalar) #negative binomial


gamlss_NB1 <- gamlss::gamlss(ortho_results$orthogroups~ortho_results$scalar, family = "NBI") 
gamlss_NB2 <- gamlss::gamlss(ortho_results$orthogroups~ortho_results$scalar, family = "NBII")

```




